"""
PharmaPOS NG - Sales Service

This module handles receipt generation, payment processing, and sales finalization.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Optional, List
from sqlalchemy.orm import Session

from .base_service import BaseService


# --- Receipt Generator -------------------------------------------------------
class ReceiptGenerator:
    """Generates formatted receipts from sales data."""

    @staticmethod
    def generate_receipt(sale_data: dict, items: List[dict], store: dict, user: dict) -> str:
        """Generate a formatted receipt string."""
        lines = []
        lines.append("=" * 50)
        lines.append(f"{'PHARMACY RECEIPT':^50}")
        lines.append(f"{store['name']:<50}")
        lines.append(f"{store['address']:<50}")
        lines.append("=" * 50)
        lines.append("")

        # Receipt info
        lines.append(f"Receipt #: {sale_data['receipt_number']}")
        lines.append(f"Date/Time: {sale_data['created_at']}")
        lines.append(f"Cashier: {user['username']}")
        lines.append("-" * 50)

        # Items header
        lines.append(f"{'Item':<25} {'Qty':<5} {'Price':>10} {'Total':>10}")
        lines.append("-" * 50)

        # Items
        total = Decimal("0")
        for item in items:
            quantity = item["quantity"]
            unit_price = Decimal(str(item["unit_price"]))
            item_total = quantity * unit_price
            total += item_total
            
            # Get product name (simplified)
            product_name = f"Product {item['product_batch_id']}"[:25]
            lines.append(
                f"{product_name:<25} {quantity:<5} {unit_price:>10.2f} {item_total:>10.2f}"
            )

        lines.append("-" * 50)
        lines.append(f"{'SUBTOTAL':<40} {total:>10.2f}")

        # Totals
        amount_paid = Decimal(str(sale_data["amount_paid"]))
        change = Decimal(str(sale_data["change_amount"]))
        
        lines.append(f"{'TOTAL AMOUNT':<40} {total:>10.2f}")
        lines.append(f"{'Amount Paid':<40} {amount_paid:>10.2f}")
        lines.append(f"{'Change':<40} {change:>10.2f}")
        lines.append(f"{'Payment Method':<40} {sale_data['payment_method']:<10}")

        lines.append("=" * 50)
        lines.append(f"{'Thank you for your patronage!':^50}")
        lines.append(f"{'Generated by PharmaPOS NG':^50}")
        lines.append("=" * 50)

        return "\n".join(lines)


# --- Payment Processor -------------------------------------------------------
class PaymentProcessor:
    """Processes different payment methods."""

    PAYMENT_METHODS = ["cash", "card", "transfer", "paystack", "flutterwave"]

    @staticmethod
    def validate_payment(
        total_amount: Decimal,
        amount_paid: Decimal,
        payment_method: str,
    ) -> tuple[bool, str]:
        """Validate payment details."""
        if payment_method not in PaymentProcessor.PAYMENT_METHODS:
            return False, f"Invalid payment method: {payment_method}"

        if amount_paid < total_amount:
            return False, f"Insufficient payment. Required: {total_amount}, Received: {amount_paid}"

        return True, "Payment valid"

    @staticmethod
    def process_cash_payment(
        total_amount: Decimal, amount_paid: Decimal
    ) -> tuple[bool, Decimal]:
        """Process cash payment and calculate change."""
        if amount_paid < total_amount:
            return False, Decimal("0")
        change = amount_paid - total_amount
        return True, change

    @staticmethod
    def process_card_payment(
        total_amount: Decimal, card_number: str, cvv: str
    ) -> tuple[bool, str]:
        """Process card payment (mock implementation)."""
        # In production, this would integrate with a payment gateway
        if len(card_number) != 16:
            return False, "Invalid card number"
        if len(cvv) != 3:
            return False, "Invalid CVV"
        return True, "Payment processed successfully"

    @staticmethod
    def process_transfer_payment(
        total_amount: Decimal, reference: str
    ) -> tuple[bool, str]:
        """Process transfer payment (mock implementation)."""
        if not reference:
            return False, "Transfer reference required"
        return True, "Transfer recorded"


# --- Sales Service -----------------------------------------------------------
class SalesService(BaseService):
    """Handles complete sales transaction lifecycle."""

    def __init__(self, session: Optional[Session] = None):
        """
        Initialize sales service.
        
        Args:
            session: SQLAlchemy database session
        """
        super().__init__(session)

    def add_item_to_cart(
        self, cart: List[dict], batch_id: int, quantity: int
    ) -> tuple[bool, str, List[dict]]:
        """
        Add item to cart.
        
        Args:
            cart: Current shopping cart
            batch_id: Product batch ID
            quantity: Quantity to add
            
        Returns:
            Tuple of (success, message, updated_cart)
        """
        from desktop_app.models import InventoryService
        
        inventory_service = InventoryService(self.session)
        batch = inventory_service.get_batch(batch_id)
        if not batch:
            return False, "Batch not found", cart

        if batch["quantity"] < quantity:
            return (
                False,
                f"Insufficient stock. Available: {batch['quantity']}, Requested: {quantity}",
                cart,
            )

        # Check if batch already in cart
        for item in cart:
            if item["batch_id"] == batch_id:
                item["quantity"] += quantity
                return True, "Item quantity updated", cart

        # Add new item
        cart.append({
            "batch_id": batch_id,
            "quantity": quantity,
            "unit_price": float(batch["cost_price"] or 0),
        })
        return True, "Item added to cart", cart

    def remove_item_from_cart(
        self, cart: List[dict], batch_id: int
    ) -> tuple[bool, str, List[dict]]:
        """
        Remove item from cart.
        
        Args:
            cart: Current shopping cart
            batch_id: Product batch ID to remove
            
        Returns:
            Tuple of (success, message, updated_cart)
        """
        cart = [item for item in cart if item["batch_id"] != batch_id]
        return True, "Item removed from cart", cart

    def calculate_cart_total(self, cart: List[dict]) -> Decimal:
        """
        Calculate total for cart items.
        
        Args:
            cart: Shopping cart
            
        Returns:
            Total amount
        """
        total = Decimal("0")
        for item in cart:
            item_total = Decimal(str(item["quantity"])) * Decimal(str(item["unit_price"]))
            total += item_total
        return total

    def finalize_sale(
        self,
        user_id: int,
        store_id: int,
        cart: List[dict],
        payment_method: str,
        amount_paid: Decimal,
        payment_reference: Optional[str] = None,
        gateway_response: Optional[str] = None,
    ) -> tuple[bool, str, Optional[dict]]:
        """
        Complete the sale transaction.
        """
        if not cart:
            return False, "Cart is empty", None

        total = self.calculate_cart_total(cart)

        # Validate payment
        is_valid, message = PaymentProcessor.validate_payment(
            total, amount_paid, payment_method
        )
        if not is_valid:
            return False, message, None

        try:
            from desktop_app.models import SalesService as ModelSalesService
            
            # Create sale using model service
            sales_service = ModelSalesService(self.session)
            sale = sales_service.create_sale(
                user_id=user_id,
                store_id=store_id,
                items=cart,
                payment_method=payment_method,
                amount_paid=amount_paid,
                payment_reference=payment_reference,
                gateway_response=gateway_response,
            )
            return True, "Sale completed successfully", sale
        except Exception as e:
            return False, f"Sale failed: {str(e)}", None

    def suspend_sale(
        self,
        user_id: int,
        store_id: int,
        cart: List[dict],
        reference: Optional[str] = None
    ) -> tuple[bool, str, Optional[int]]:
        """
        Suspend a sale (On-Hold).
        """
        if not cart:
            return False, "Cart is empty", None

        try:
            from desktop_app.database import suspended_sales, suspended_sale_items
            
            total = self.calculate_cart_total(cart)
            
            # Create suspended sale record
            ss_stmt = suspended_sales.insert().values(
                reference=reference,
                total_amount=total,
                user_id=user_id,
                store_id=store_id,
            )
            result = self.session.execute(ss_stmt)
            suspended_id = result.inserted_primary_key[0]
            
            # Add items
            for item in cart:
                item_stmt = suspended_sale_items.insert().values(
                    suspended_sale_id=suspended_id,
                    product_batch_id=item['batch_id'],
                    quantity=item['quantity'],
                    unit_price=item['unit_price']
                )
                self.session.execute(item_stmt)
                
            self.session.commit()
            return True, "Sale suspended successfully", suspended_id
        except Exception as e:
            self.session.rollback()
            return False, f"Failed to suspend sale: {str(e)}", None

    def get_suspended_sales(self, store_id: int) -> List[dict]:
        """Get all suspended sales for a store."""
        from desktop_app.database import suspended_sales
        from sqlalchemy import select
        
        stmt = select(suspended_sales).where(suspended_sales.c.store_id == store_id).order_by(suspended_sales.c.created_at.desc())
        results = self.session.execute(stmt).fetchall()
        return [dict(row._mapping) for row in results]

    def get_suspended_sale_items(self, suspended_id: int) -> List[dict]:
        """Get items for a suspended sale."""
        from desktop_app.database import suspended_sale_items, product_batches, products
        from sqlalchemy import select, join
        
        # Use a join to get batch and product details for reconstruction
        j = join(suspended_sale_items, product_batches, suspended_sale_items.c.product_batch_id == product_batches.c.id).join(
            products, product_batches.c.product_id == products.c.id
        )
        stmt = select(
            suspended_sale_items.c.id,
            suspended_sale_items.c.product_batch_id.label('batch_id'),
            suspended_sale_items.c.quantity,
            suspended_sale_items.c.unit_price.label('price'),
            product_batches.c.batch_number,
            products.c.name.label('product_name')
        ).select_from(j).where(suspended_sale_items.c.suspended_sale_id == suspended_id)
        
        results = self.session.execute(stmt).fetchall()
        return [dict(row._mapping) for row in results]

    def delete_suspended_sale(self, suspended_id: int) -> bool:
        """Delete a suspended sale after recall."""
        from desktop_app.database import suspended_sales
        from sqlalchemy import delete
        
        try:
            stmt = delete(suspended_sales).where(suspended_sales.c.id == suspended_id)
            self.session.execute(stmt)
            self.session.commit()
            return True
        except Exception as e:
            self.session.rollback()
            print(f"Delete failed: {e}")
            return False


__all__ = [
    "ReceiptGenerator",
    "PaymentProcessor",
    "SalesService",
]
